ITAW000/Controllers/RegraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ITAW000.Models;
using ITAW000.Repository;

namespace ITAW000.Controllers
{
    public class RegraController : Controller
    {
        private RegraRepository regraRespository = new RegraRepository();
        private RetornoRepository retornoRespository = new RetornoRepository();
        private ResponsavelRepository responsavelRespository = new ResponsavelRepository();
        private TipoRepository tipoRespository = new TipoRepository();
        private SituacaoRepository situacaoRepository = new SituacaoRepository();
        private SistemaRepository sistemaRepository = new SistemaRepository();
               
        // GET: Regra
        public ActionResult Index()
        {
            return View(regraRespository.GetAll());
        }

        // GET: Regra/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Regra/Create
        public ActionResult Create()
        {
            CarregaDropDrow();
            return View();
        }


        public void CarregaDropDrow()
        {
            List<SelectListItem> ListSistema = new List<SelectListItem>
            {
                new SelectListItem() { Value = "-1", Text = "" }
            };

            ListSistema.AddRange(sistemaRepository.GetAll().Select(x =>
                                 new SelectListItem()
                                 {
                                     Value = x.IdSistema.ToString(),
                                     Text = x.NomeSistema
                                 }).ToList());

            ViewBag.ListSistema = ListSistema;


            List<SelectListItem> ListRetorno = new List<SelectListItem>
            {
                new SelectListItem() { Value = "-1", Text = "" }
            };

            ListRetorno.AddRange(retornoRespository.GetAll().Select(x =>
                                 new SelectListItem()
                                 {
                                     Value = x.IdRetorno.ToString(),
                                     Text = x.NomeRetorno
                                 }).ToList());

            ViewBag.ListRetorno = ListRetorno;

            List<SelectListItem> ListResponsavel = new List<SelectListItem>
            {
                new SelectListItem() { Value = "-1", Text = "" }
            };

            ListResponsavel.AddRange(responsavelRespository.GetAll().Select(x =>
                                 new SelectListItem()
                                 {
                                     Value = x.IdResponsavel.ToString(),
                                     Text = x.NomeResponsavel
                                 }).ToList());

            ViewBag.ListResponsavel = ListResponsavel;


            List<SelectListItem> ListTipo = new List<SelectListItem>
            {
                new SelectListItem() { Value = "-1", Text = "" }
            };

            ListTipo.AddRange(tipoRespository.GetAll().Select(x =>
                                 new SelectListItem()
                                 {
                                     Value = x.IdTipo.ToString(),
                                     Text = x.NomeTipo
                                 }).ToList());

            ViewBag.ListTipo = ListTipo;

            List<SelectListItem> ListSituacao = new List<SelectListItem>
            {
                new SelectListItem() { Value = "-1", Text = "" }
            };

            ListSituacao.AddRange(situacaoRepository.GetAll().Select(x =>
                                 new SelectListItem()
                                 {
                                     Value = x.IdSituacao.ToString(),
                                     Text = x.NomeSituacao
                                 }).ToList());

            ViewBag.ListSituacao = ListSituacao;
        }

        // POST: Regra/Create
        [HttpPost]
        public ActionResult Create(Regra objModel)
        {
            try
            {
                regraRespository.Add(objModel);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Regra/Edit/5
        public ActionResult Edit(int id)
        {
            CarregaDropDrow();

            var objModel = regraRespository.GetById(id);
         //    return Json(objModel, JsonRequestBehavior.AllowGet);

            return View(objModel);
        }

        // POST: Regra/Edit/5
        [HttpPost]
        public ActionResult Edit(Regra objModel)
        {
            try
            {
                regraRespository.Update(objModel);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Regra/Delete/5
        public ActionResult DeleteRegra(int id)
        {
            regraRespository.DeleteById(id);

            return RedirectToAction("Index");
        }

        // POST: Regra/Delete/5
        [HttpPost]
        public ActionResult DeleteRegra(int id, FormCollection collection)
        {
            try
            {
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        



    }
}

ITAW000/Controllers/RetornoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ITAW000.Models;
using ITAW000.Repository;

namespace ITAW000.Controllers
{
    public class RetornoController : Controller
    {
        private readonly RetornoRepository respository = new RetornoRepository();

        // GET: Regra
        public ActionResult Index()
        {
            return View(respository.GetAll());
        }

        // GET: Regra/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Regra/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Regra/Create
        [HttpPost]
        public ActionResult Create(Retorno objModel)
        {
            try
            {
                respository.Add(objModel);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Regra/Edit/5
        public JsonResult Edit(int id)
        {
            var objModel = respository.GetById(id);
            return Json(objModel, JsonRequestBehavior.AllowGet);

        }

        // POST: Regra/Edit/5
        [HttpPost]
        public ActionResult Edit(Retorno objModel)
        {
            try
            {
                respository.Update(objModel);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Regra/Delete/5
        public ActionResult Delete(Retorno objModel)
        {
            respository.DeleteById(objModel.IdRetorno);

            return RedirectToAction("Index");
        }

        // POST: Regra/Delete/5
        [HttpPost]
        public ActionResult DeleteRegra(int id, Tipo objModel)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ITAW000/Controllers/SistemaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ITAW000.Models;
using ITAW000.Repository;

namespace ITAW000.Controllers
{
    public class SistemaController : Controller
    {
        private readonly SistemaRepository respository = new SistemaRepository();

        // GET: Regra
        public ActionResult Index()
        {
            return View(respository.GetAll());
        }

        // GET: Regra/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Regra/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Regra/Create
        [HttpPost]
        public ActionResult Create(Sistema objModel)
        {
            try
            {
                respository.Add(objModel);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Regra/Edit/5
        public JsonResult Edit(int id)
        {
            var objModel = respository.GetById(id);
            return Json(objModel, JsonRequestBehavior.AllowGet);

        }

        // POST: Regra/Edit/5
        [HttpPost]
        public ActionResult Edit(Sistema objModel)
        {
            try
            {
                respository.Update(objModel);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Regra/Delete/5
        public ActionResult Delete(Sistema objModel)
        {
            respository.DeleteById(objModel.IdSistema);

            return RedirectToAction("Index");
        }

        // POST: Regra/Delete/5
        [HttpPost]
        public ActionResult DeleteRegra(int id, Tipo objModel)
        {
            try
            {
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ITAW000/Controllers/TipoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ITAW000.Models;
using ITAW000.Repository;

namespace ITAW000.Controllers
{
    public class TipoController : Controller
    {
        private readonly TipoRepository respository = new TipoRepository();

        // GET: Regra
        public ActionResult Index()
        {
            return View(respository.GetAll());
        }

        // GET: Regra/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Regra/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Regra/Create
        [HttpPost]
        public ActionResult Create(Tipo objModel)
        {
            try
            {
                respository.Add(objModel);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Regra/Edit/5
        public JsonResult Edit(int id)
        {
            var objModel = respository.GetById(id);
            return Json(objModel, JsonRequestBehavior.AllowGet);

        }

        // POST: Regra/Edit/5
        [HttpPost]
        public ActionResult Edit(Tipo objModel)
        {
            try
            {
                respository.Update(objModel);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Regra/Delete/5
        public ActionResult Delete(Tipo objModel)
        {
            respository.DeleteById(objModel.IdTipo);

            return RedirectToAction("Index");
        }

        // POST: Regra/Delete/5
        [HttpPost]
        public ActionResult DeleteRegra(int id, Tipo objModel)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ITAW000/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link rel="stylesheet" href="//malihu.github.io/custom-scrollbar/jquery.mCustomScrollbar.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


   

    <link rel="stylesheet" href="~/Content/css/main.css">
    <link rel="stylesheet" href="~/Content/css/side-bar-theme.css">

    <title>@ViewBag.Title - App Classificação</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <div class="page-wrapper default-theme sidebar-bg bg1 toggled">
        <nav id="sidebar" class="sidebar-wrapper">
            <div class="sidebar-content">
                <!-- sidebar-brand  -->
                <div class="sidebar-item sidebar-brand">
                    <Span class="title">Monitor 431 - 987 </Span> 
                 </div>

                <!-- sidebar-header  -->
                <div class="sidebar-item sidebar-header d-flex flex-nowrap">
                    <div class="user-pic">
                        <img class="img-responsive img-rounded" src="~/Images/usuario.png" alt="User picture">
                    </div>
                    <div class="user-info">
                        <span class="user-name">
                            Anderson
                            <strong>Barreto</strong>
                        </span>
                        <span class="user-role">Administrator</span>
                        <span class="user-status">
                            <i class="fa fa-circle"></i>
                            <span>Online</span>
                        </span>
                    </div>

                </div>


                <!-- sidebar-menu  -->
                <div class=" sidebar-item sidebar-menu">
                    <ul>
                        <li class="header-menu">
                            <span>Geral</span>
                        </li>
                        <li class="sidebar-dropdown">
                            <a href="#">
                                <i class="glyphicon glyphicon-home"></i>
                                <span class="menu-text">Dashboard</span>

                            </a>
                            <div class="sidebar-submenu">
                                <ul>
                                    <li>
                                        <a href="@Url.Action("index", "Home")">
                                            <i class="glyphicon glyphicon-home"></i>
                                            Dashboard 431
                                        </a>
                                    </li>

                                    <li>
                                        <a href="@Url.Action("index", "Home")">
                                            <i class="glyphicon glyphicon-home"></i>
                                            Dashboard 987
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </li>

                        <li class="sidebar-dropdown">
                            <a href="#">
                                <i class="glyphicon glyphicon-th"></i>
                                <span class="menu-text">Dominios</span>
                            </a>
                            <div class="sidebar-submenu">
                                <ul>
                                    <li><a href="@Url.Action("index", "Responsavel")"> <i class="glyphicon glyphicon-user"></i>Responsavel</a></li>
                                    <li><a href="@Url.Action("index", "Retorno")"> <i class="glyphicon glyphicon-share-alt"></i>Retorno</a></li>
                                    <li><a href="@Url.Action("index", "Sistema")"> <i class="glyphicon glyphicon-modal-window"></i>Sistema</a></li>
                                    <li><a href="@Url.Action("index", "Situacao")"> <i class="glyphicon glyphicon-flag"></i>Situação</a></li>
                                    <li><a href="@Url.Action("index", "Tipo")"> <i class="glyphicon glyphicon-tags"></i>Tipo</a></li>
                                </ul>
                            </div>
                        </li>
                        <li class="header-menu">
                            <span>Menu 431</span>
                        </li>
                        <li class="sidebar-dropdown">
                            <a href="#">
                                <i class="glyphicon glyphicon-th-list"></i>
                                <span class="menu-text">Classificação</span>
                            </a>
                            <div class="sidebar-submenu">
                                <ul>
                                    <li><a href="@Url.Action("index", "Pendencias")"> <i class="glyphicon glyphicon-arrow-down"></i>A classificar</a></li>
                                    <li><a href="@Url.Action("Lista", "Pendencias")"> <i class="glyphicon glyphicon-arrow-up"></i>Classificados</a></li>
                                </ul>
                            </div>
                        </li>
                        <li>
                            <a href="@Url.Action("index", "Regra")">
                                <i class="glyphicon glyphicon-sort"></i>
                                <span class="menu-text">Regra</span>
                            </a>
                        </li>

                        <li>
                            <a href="@Url.Action("index", "Historico")">
                                <i class="glyphicon glyphicon-transfer"></i>
                                <span class="menu-text">Histórico</span>
                            </a>
                        </li>

                        <li class="header-menu">
                            <span>Menu 987</span>
                        </li>

                    </ul>
                </div>
                <!-- sidebar-menu  -->
            </div>
            <!-- sidebar-footer  -->
            <div class="sidebar-footer">
                <div style="text-align:center">
                   
                </div>

            </div>
        </nav>
        <!-- page-content  -->

        <main class="page-content pt-0">
            <nav class="navbar navbar-expand-md  ">
                <button id="pin-sidebar" class="btn btn-info navbar-btn">
                    <i class="glyphicon glyphicon-align-justify"></i>
                </button>
                <div class="navbar-header">                  
                    <div class="hero-image"> <img src="~/images/logo.png" alt="" style="max-width:720px;" /></div>
                </div>

                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="@Url.Action("Contact", "Home")"><i class="glyphicon glyphicon-cog "></i></a></li>
                        <li><a href="@Url.Action("About", "Home")"><i class="glyphicon glyphicon-info-sign"></i></a></li>
                    </ul>
                </div>
            </nav>
            <div id="overlay" class="overlay"></div>

            <div class="container-fluid p-4">
                @RenderBody()
            </div>
        </main>
        <!-- page-content" -->
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
   @* <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>*@
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
          <script src="//malihu.github.io/custom-scrollbar/jquery.mCustomScrollbar.concat.min.js"></script>

    <script src="~/Scripts/js/main.js"></script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


</body>
</html>