ITAW000/Models/Situacao.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ITAW000.Models
{
    public class Situacao
    {
        public int IdSituacao { get; set; }
        [Required(ErrorMessage = "Favor preencher o campo nome")]
        public string NomeSituacao { get; set; }
        [Required(ErrorMessage = "Favor preencher o campo descrição")]
        public string DescSituacao { get; set; }
        public DateTime DtInclusao { get; set; }
        public DateTime DtAlteracao { get; set; }
        public string Usuario { get; set; }
    }
}

ITAW000/Controllers/SituacaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ITAW000.Models;
using ITAW000.Repository;

namespace ITAW000.Controllers
{
    public class SituacaoController : Controller
    {
        private readonly SituacaoRepository respository = new SituacaoRepository();

        // GET: Regra
        public ActionResult Index()
        {
            return View(respository.GetAll());
        }

        // GET: Regra/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Regra/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Regra/Create
        [HttpPost]
        public ActionResult Create(Situacao objModel)
        {
            try
            {
                respository.Add(objModel);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Regra/Edit/5
        public JsonResult Edit(int id)
        {
            var objModel = respository.GetById(id);
            return Json(objModel, JsonRequestBehavior.AllowGet);

        }

        // POST: Regra/Edit/5
        [HttpPost]
        public ActionResult Edit(Situacao objModel)
        {
            try
            {
                respository.Update(objModel);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Regra/Delete/5
        public ActionResult Delete(Situacao objModel)
        {
            respository.DeleteById(objModel.IdSituacao);

            return RedirectToAction("Index");
        }

        // POST: Regra/Delete/5
        [HttpPost]
        public ActionResult DeleteRegra(int id, Situacao objModel)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ITAW000/Views/Situacao/Index.cshtml
@model IEnumerable<ITAW000.Models.Situacao>

@{
    ViewBag.Title = "Situação";
}

<script>
    function GetDetails(id) {
        $.ajax({
            url: "/Situacao/Edit/" + id,
            typr: "GET",
            contentType: "application/json;charset=UTF-8",
            dataType: "json",
            success: function (response) {
                $('#IdEdit').val(response.IdSituacao);
                $('#idNome').val(response.NomeSituacao);
                $('#idDescricao').val(response.DescSituacao);
                $('#editModal').modal('show');
            },
            error: function (response) {
                console.log(response);
            }
        });
        return false;
    }

    function Delete(id) {
        $('#IdDelete').val(id);
        $('#deleteModal').modal('show');
    }    
</script>

<div class="row">
    <div class="col-12">

        <div class="card-size">
            <div class="card-header">
                <i class="glyphicon glyphicon-flag"></i>
                <h3>Situações </h3>
                <p>Realação de situações cadastradas no sistema</p>
                <a href="#addModal" class="btn btn-success pull-right" data-toggle="modal">Adicionar Novo</a>
            </div>
            <div class="card-body">
                @if (@Model.Count() == 0)
                {
                    <section class="container-fluid h-100 d-flex justify-content-center">
                        <div class="jumbotron my-auto">
                            <h3 class="display-3">Nenhum item localizado!</h3>
                        </div>
                    </section>
                }
                else
                {
                    <div class="container-fluid">
                        <div class="table-responsive ">
                            <table class="table table-hover table-striped ">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th>Id</th>
                                        <th>Nome</th>
                                        <th>Descrição</th>
                                        <th>Data Inclusão</th>
                                        <th>Usuario</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                <i class="glyphicon glyphicon-flag"></i>
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.IdSituacao)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.NomeSituacao)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.DescSituacao)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.DtInclusao)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Usuario)
                                            </td>
                                            <td>
                                                <a onclick="GetDetails(@item.IdSituacao)">
                                                    <i class="fa fa-edit text-success"></i>
                                                </a>
                                                <a onclick="Delete(@item.IdSituacao)">
                                                    <i class="fa fa-trash-o text-danger"></i>
                                                </a>


                                            </td>
                                        </tr>
                                    }

                                </tbody>
                            </table>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>



<!-- Add Modal HTML -->
<div id="addModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <h4 class="modal-title">Adicionar Registro</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            @using (Html.BeginForm("Create", "Situacao", FormMethod.Post))
            {
                <div class="modal-body">
                    <div class="form-group">
                        <label>Nome</label>
                        <input type="text" class="form-control" name="NomeSituacao" required>
                    </div>
                    <div class="form-group">
                        <label>Descrição</label>
                        <input type="text" class="form-control" name="DescSituacao" required>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
                    <input type="submit" class="btn btn-success" value="Salvar">
                </div>
            }
        </div>
    </div>
</div>
<!-- Edit Modal HTML -->
<div id="editModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <h4 class="modal-title">Editar Registro</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            @using (Html.BeginForm("edit", "Situacao", FormMethod.Post))
            {
                <div class="modal-body" style="height:250px">

                    <div class="form-group">
                        <input type="hidden" class="form-control" name="idSituacao" id="IdEdit">
                    </div>

                    <div class="form-group">
                        <label>Nome</label>
                        <input type="text" class="form-control" name="NomeSituacao" id="idNome" required>
                    </div>
                    <div class="form-group">
                        <label>Descrição</label>
                        <input type="text" class="form-control" name="DescSituacao" id="idDescricao" required>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
                    <input type="submit" class="btn btn-success" value="Salvar">
                </div>
            }
        </div>
    </div>
</div>
<!-- Delete Modal HTML -->
<div id="deleteModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            @using (Html.BeginForm("Delete", "Situacao", FormMethod.Post))
            {
                <div class="modal-header">
                    <h4 class="modal-title">Apagar Registro</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="form-group">
                    <input type="hidden" class="form-control" name="idSituacao" id="IdDelete">
                </div>

                <div class="modal-body">
                    <p>Deseja Relamente excluir o item selecionado?</p>
                    <p class="text-warning"><small>Esta ação não podera ser desfeita.</small></p>
                </div>
                <div class="modal-footer">
                    <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
                    <input type="submit" class="btn btn-danger" value="Delete">
                </div>
            }
        </div>
    </div>
</div>